#!/usr/bin/env python3
import os
import time

LOG_DIR = "/var/log"
DAYS_OLD = 7
now = time.time()

for root, dirs, files in os.walk(LOG_DIR):
    for name in files:
        path = os.path.join(root, name)
        if os.stat(path).st_mtime < now - DAYS_OLD * 86400:
            print(f"Deleting old log: {path}")
            os.remove(path)
